name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Build
      - name: Build frontend
        run: npm run build:frontend
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Validate backend (syntax)
        run: node --check backend/src/server.js

      #Lint
      - name: Lint
        run: npm run lint

      # Test
      - name: Backend tests
        run: npm run test:backend

      - name: Frontend tests
        run: npm run test:frontend

      - name: Frontend tests with coverage
        run: npm run test:frontend:coverage

      - name: Backend tests with coverage
        run: npm run test:backend:coverage

      # Package
      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-code
          path: backend

      # Deploy pois p채채lt채 kun kuluu credej채
      # - name: Deploy frontend to Netlify
      #   if: github.ref == 'refs/heads/main'
      #   uses: nwtgck/actions-netlify@v3.0
      #   with:
      #     publish-dir: ./frontend/dist
      #     production-deploy: true
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # - name: Deploy backend (Render)
      #   if: github.ref == 'refs/heads/main'
      #   run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}